name = "storyblok-proxy"
main = "dist/index.mjs"
compatibility_date = "2022-05-28"
compatibility_flags = []

[build]
command = "node build.js"

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true

[env.production]
name = "storyblok-proxy"

[env.staging]
name = "stg-storyblok-proxy"

[env.development]
name = "dev-storyblok-proxy"
