name: Node CI

on:
  push:
    branches:
    - '**'
    - '!main'
    - '!development'

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
