name: release_production

on: workflow_dispatch

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  version:
    name: Version - Version
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}
    steps:
    - name: Get the version
      id: version
      uses: pondevelopment/actions/version@main

  deploy:
    name: Deploy worker to Cloudflare
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [test, version]
    steps:
    - uses: actions/checkout@master
    - name: Get developer dependencies
      run: npm ci && npm run build
    - name: Publish worker
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_PONDIGITALSOLUTIONS_ACCOUNT_ID}}
        secrets: |
            OKTA_AUDIENCE
            OKTA_ISSUER
            OKTA_CLIENTID
            STORYBLOK_HOST
            STORYBLOK_ORIGIN_TOKENS
            SENTRY_DSN
            ENVIRONMENT
            VERSION
      env:
        OKTA_AUDIENCE: ${{ secrets.OKTA_AUDIENCE }}
        OKTA_ISSUER: ${{ secrets.OKTA_ISSUER }}
        OKTA_CLIENTID: ${{ secrets.OKTA_CLIENTID }}
        STORYBLOK_HOST: ${{ secrets.STORYBLOK_HOST }}
        STORYBLOK_ORIGIN_TOKENS: ${{ secrets.STORYBLOK_ORIGIN_TOKENS }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        ENVIRONMENT: production
        VERSION: ${{ needs.version.outputs.VERSION }}
